/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ebb8450bbf7210dd3bd61b3
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";

// Custom Actions


// START IMPORT ACTIONS
import CategoryActions from "../redux/actions/CategoryActions";

// END IMPORT ACTIONS

/** APIs

* actionsCategory.create
*	@description CRUD ACTION create
*
* actionsCategory.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsCategory.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*

**/

class CategoryEdit extends Component {
  // Init category
  constructor(props) {
    super(props);
    this.state = {
      category: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsCategory.loadCategory(this.props.match.params.id);
    }
    
  }

  // Insert props category in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      category: props.category
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.category._id) {
      this.props.actionsCategory.saveCategory(this.state.category).then(data => {
        this.props.history.push("/categorys/");
      });
    } else {
      this.props.actionsCategory.createCategory(this.state.category).then(data => {
        this.props.history.push("/categorys/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Category Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="category_name"
            label="Category_name"
            value={this.state.category.category_name || ""}
            onChange={Utils.handleChange.bind(this, "category")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.category.category_name && this.state.category.category_name === ""
              ? { error: true }
              : {})}
          />
          

          {/* Footer */}
          <div className="footer-card">
            <Link to="/categorys/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsCategory: bindActionCreators(CategoryActions, dispatch),
  };
};

// Validate types
CategoryEdit.propTypes = { 
  actionsCategory: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    category: state.CategoryEditReducer.category
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CategoryEdit);
